// Builds the Japanese font slices from the content packs and writes src/app/styles/fonts.css.
// Base slice: kana, punctuation, ASCII. Level slices: every CJK character a level's packs use.
// Pure Node (harfbuzz via subset-font), so it runs on Windows, macOS and Linux.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

import subsetFont from 'subset-font'

const PACKS = 'public/packs/ja'
const OUT = 'public/fonts'
const LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1']
const CJK = /[㐀-䶿一-鿿豈-﫿]/u

const faces = [
  // Body face: every level slice. Bold body face: base slice only (Japanese bold is used for
  // kana UI labels; kanji are never set bold). Hero face: every level slice.
  {
    family: 'Zen Kaku Gothic New',
    id: 'zkgn',
    weight: 400,
    slices: 'all',
    file: 'node_modules/@fontsource/zen-kaku-gothic-new/files/zen-kaku-gothic-new-japanese-400-normal.woff2',
  },
  {
    family: 'Zen Kaku Gothic New',
    id: 'zkgn',
    weight: 700,
    slices: 'base',
    file: 'node_modules/@fontsource/zen-kaku-gothic-new/files/zen-kaku-gothic-new-japanese-700-normal.woff2',
  },
  {
    family: 'Shippori Mincho',
    id: 'shippori',
    weight: 700,
    slices: 'all',
    file: 'node_modules/@fontsource/shippori-mincho/files/shippori-mincho-japanese-700-normal.woff2',
  },
]
const latin = [
  {
    family: 'Instrument Sans',
    weight: '400',
    file: 'node_modules/@fontsource/instrument-sans/files/instrument-sans-latin-400-normal.woff2',
    out: 'instrument-sans-400.woff2',
  },
  {
    family: 'Instrument Sans',
    weight: '500',
    file: 'node_modules/@fontsource/instrument-sans/files/instrument-sans-latin-500-normal.woff2',
    out: 'instrument-sans-500.woff2',
  },
  {
    family: 'Instrument Sans',
    weight: '600',
    file: 'node_modules/@fontsource/instrument-sans/files/instrument-sans-latin-600-normal.woff2',
    out: 'instrument-sans-600.woff2',
  },
  {
    family: 'Fraunces Variable',
    weight: '100 900',
    file: 'node_modules/@fontsource-variable/fraunces/files/fraunces-latin-opsz-normal.woff2',
    out: 'fraunces-variable.woff2',
  },
]

function range(from, to) {
  const out = []
  for (let c = from; c <= to; c++) out.push(String.fromCodePoint(c))
  return out.join('')
}
const BASE_TEXT =
  range(0x20, 0x7e) + // ASCII
  range(0x3000, 0x303f) + // CJK punctuation
  range(0x3041, 0x3096) +
  range(0x3099, 0x309f) + // hiragana
  range(0x30a0, 0x30ff) + // katakana
  range(0xff01, 0xff5e) +
  range(0xff61, 0xff9f) + // fullwidth / halfwidth forms
  '—…‘’“”·–×※○●→←々〜～'

function levelTexts() {
  const seen = new Set([...BASE_TEXT])
  const result = {}
  for (const level of LEVELS) {
    const chars = new Set()
    const kanji = JSON.parse(readFileSync(join(PACKS, `kanji-${level}.json`), 'utf8')).items
    for (const k of kanji) chars.add(k.char)
    const vocab = JSON.parse(readFileSync(join(PACKS, `vocab-${level}.json`), 'utf8')).items
    // Only the spellings the app shows: the first form and any form JMdict marks common.
    for (const v of vocab) {
      v.forms.forEach((f, i) => {
        if (i === 0 || f.common) for (const ch of f.text) if (CJK.test(ch)) chars.add(ch)
      })
    }
    const fresh = [...chars].filter((c) => !seen.has(c)).sort()
    for (const c of fresh) seen.add(c)
    result[level] = fresh.join('')
  }
  return result
}

function unicodeRange(text) {
  const points = [...new Set([...text].map((c) => c.codePointAt(0)))].sort((a, b) => a - b)
  const ranges = []
  let start = points[0]
  let prev = points[0]
  for (const p of points.slice(1)) {
    if (p === prev + 1) {
      prev = p
      continue
    }
    ranges.push(
      start === prev ? `U+${start.toString(16)}` : `U+${start.toString(16)}-${prev.toString(16)}`,
    )
    start = prev = p
  }
  ranges.push(
    start === prev ? `U+${start.toString(16)}` : `U+${start.toString(16)}-${prev.toString(16)}`,
  )
  return ranges.join(',')
}

mkdirSync(OUT, { recursive: true })
for (const stale of readdirSync(OUT)) unlinkSync(join(OUT, stale))

const slices = { base: BASE_TEXT, ...levelTexts() }
const css = [
  '/* Generated by scripts/fonts/subset.mjs from public/packs. Do not edit by hand. */',
  '/* Fonts are SIL Open Font License 1.1; see public/fonts/LICENSES.txt. */',
]
let total = 0
for (const face of faces) {
  const source = readFileSync(face.file)
  for (const [slice, textOfSlice] of Object.entries(slices)) {
    if (!textOfSlice || (face.slices === 'base' && slice !== 'base')) continue
    const buffer = await subsetFont(source, textOfSlice, { targetFormat: 'woff2' })
    const name = `${face.id}-${face.weight}-${slice.toLowerCase()}.woff2`
    writeFileSync(join(OUT, name), buffer)
    total += buffer.length
    console.log(
      `${name.padEnd(28)} ${(buffer.length / 1024).toFixed(1).padStart(7)} KB  ${[...textOfSlice].length} chars`,
    )
    css.push(
      `@font-face { font-family: '${face.family}'; font-style: normal; font-weight: ${face.weight}; font-display: swap; src: url('/fonts/${name}') format('woff2'); unicode-range: ${unicodeRange(textOfSlice)}; }`,
    )
  }
}
// Latin faces are cut down to the characters the UI can show: ASCII, Latin-1 Supplement,
// general punctuation, arrows, euro and minus. Variable axes survive subsetting.
const LATIN_TEXT =
  range(0x20, 0x7e) +
  range(0xa0, 0xff) +
  range(0x2010, 0x2027) +
  range(0x2030, 0x203a) +
  range(0x2190, 0x2199) +
  '\u20ac\u2212\u2022\u2026\u00d7'
for (const l of latin) {
  if (!existsSync(l.file)) throw new Error(`missing ${l.file}`)
  const subset = await subsetFont(readFileSync(l.file), LATIN_TEXT, { targetFormat: 'woff2' })
  writeFileSync(join(OUT, l.out), subset)
  const bytes = subset.length
  total += bytes
  console.log(`${l.out.padEnd(28)} ${(bytes / 1024).toFixed(1).padStart(7)} KB`)
  // Latin faces use font-display: optional so a slow first load paints the fallback immediately and
  // never re-flows; the service worker caches them, so every later visit shows the brand faces.
  css.push(
    `@font-face { font-family: '${l.family}'; font-style: normal; font-weight: ${l.weight}; font-display: optional; src: url('/fonts/${l.out}') format('woff2'); unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD; }`,
  )
}
writeFileSync('src/app/styles/fonts.css', css.join('\n') + '\n')
writeFileSync(
  join(OUT, 'LICENSES.txt'),
  [
    'All fonts in this folder are licensed under the SIL Open Font License 1.1 (https://openfontlicense.org).',
    'They are subsets built from the Fontsource packages; the original licence files are:',
    'Zen Kaku Gothic New: node_modules/@fontsource/zen-kaku-gothic-new/LICENSE (Copyright 2022 The Zen Project Authors)',
    'Shippori Mincho: node_modules/@fontsource/shippori-mincho/LICENSE (Copyright 2020 The Shippori Mincho Project Authors)',
    'Instrument Sans: node_modules/@fontsource/instrument-sans/LICENSE (Copyright 2022 The Instrument Sans Project Authors)',
    'Fraunces: node_modules/@fontsource-variable/fraunces/LICENSE (Copyright 2019 The Fraunces Project Authors)',
  ].join('\n') + '\n',
)
console.log(`total ${(total / 1024).toFixed(0)} KB in ${OUT}`)
